### ISSUE TITLE
FAQ 변경사항

### ISSUE THREAD

**Issue by PeterPPark** [JBNU-LIKELION-INTRO-PROJ/8th-intro-page#22]
1. 일자 추가를 notion에 공지한 데로 등록해주시면 감사하겠습니다.
2. FAQ에서  기획에서부터는~ 이라는 문구가 있는데 기획은~ 이라고 변경해주시면 감사하겠습니다.
3. 지원하기 링크를 구글 폼이랑 같이 연동해 주시길 바랍니다.

**Comment by CaesiumY** [comment]
혹시 구글폼 링크 좀 올려주실 수 있으신가요?

**Comment by PeterPPark** [comment]
https://forms.gle/yqFkpiVpoHZEo57q9

구글 폼 링크입니다!

**Comment by CaesiumY** [comment]
배포 완료했습니다 확인해주세요!

**Comment by PeterPPark** [comment]
​
확인 했습니다! 감사해요!
-----Original Message-----
