### ISSUE TITLE
운영진 준혁씨 gitlab 링크도 추가 부탁드립니다.

### ISSUE THREAD

**Issue by PeterPPark** [JBNU-LIKELION-INTRO-PROJ/8th-intro-page#24]
준혁씨 gitlab 주소입니다: https://gitlab.com/CitrusSoda

감사합니다.

**Comment by PeterPPark** [comment]
assign 드렸습니다.

**Comment by CaesiumY** [comment]
https://github.com/JBNU-LIKELION-INTRO-PROJ/8th-intro-page/commit/efa8ec9a8657cfe9376306df870ebe7539c45dcb

각 운영진의 links 에 아이템을 넣으면 반응하여 알아서 버튼이 생기도록 적용했습니다
